name: Formatting Checks and Markdown Linting

on:
  pull_request:
    branches:
      - main
      - trunk

jobs:
  prettier-fmt-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Prettier
        run: npm install --save-dev prettier

      - name: Check formatting with Prettier
        run: npx prettier --check "**/*.md" --config ./.config/.prettierrc

  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli

      - name: Run markdownlint
        run: markdownlint '**/*.md' --config ./.config/.markdownlint.yaml